# Generated by Django 4.2.3 on 2023-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='landing/project_images/'),
        ),
    ]
